name: ladydyze
favicon: null
layout_spectrum: 0.8518121689558029
typography_spectrum: 0.20577368536032736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.17715625721029937
  lightness: 0.20230601029470563
  saturation: 0.6960371546447277
  rhythmicContrast: 0.6064412810374051
purpose: []
